import type { OutputFormat } from '@/types'

interface PackData {
  title: string
  description?: string | null
  frameworkTag?: string | null
  languageTag?: string | null
  uiLib?: string | null
  db?: string | null
  hosting?: string | null
  architecture?: string | null
  conventions?: string | null
  aiRules?: string | null
  gotchas?: string | null
}

function buildMarkdownBody(pack: PackData): string {
  const sections: string[] = []

  if (pack.frameworkTag || pack.languageTag || pack.uiLib || pack.db || pack.hosting) {
    const stackLines: string[] = []
    if (pack.frameworkTag) stackLines.push(`Framework: ${pack.frameworkTag}`)
    if (pack.languageTag) stackLines.push(`Language: ${pack.languageTag}`)
    if (pack.uiLib) stackLines.push(`UI Library: ${pack.uiLib}`)
    if (pack.db) stackLines.push(`Database: ${pack.db}`)
    if (pack.hosting) stackLines.push(`Hosting: ${pack.hosting}`)
    sections.push(`## Tech Stack\n\n${stackLines.join('\n')}`)
  }

  if (pack.architecture?.trim()) {
    sections.push(`## Architecture & Structure\n\n${pack.architecture.trim()}`)
  }
  if (pack.conventions?.trim()) {
    sections.push(`## Coding Conventions\n\n${pack.conventions.trim()}`)
  }
  if (pack.aiRules?.trim()) {
    sections.push(`## AI Behaviour Rules\n\n${pack.aiRules.trim()}`)
  }
  if (pack.gotchas?.trim()) {
    sections.push(`## Known Gotchas & Quirks\n\n${pack.gotchas.trim()}`)
  }

  return sections.join('\n\n---\n\n')
}

export function generateOutput(format: OutputFormat, pack: PackData): string {
  const body = buildMarkdownBody(pack)
  const desc = pack.description ? `\n\n> ${pack.description}` : ''

  switch (format) {
    case 'CLAUDE.md':
      return `# ${pack.title}${desc}\n\n> This CLAUDE.md file was generated by Contxt.\n> Place it in your project root for Claude Code to auto-load.\n\n${body}`

    case '.cursorrules':
      return `# Cursor Rules — ${pack.title}\n\n# Generated by Contxt\n${desc}\n\n${body}`

    case 'Markdown':
      return `# AI Context Pack — ${pack.title}\n\n_Generated by Contxt_\n${desc}\n\n${body}`

    case 'JSON':
      return JSON.stringify(
        {
          title: pack.title,
          description: pack.description,
          generated_by: 'Contxt',
          stack: {
            framework: pack.frameworkTag,
            language: pack.languageTag,
            uiLib: pack.uiLib,
            db: pack.db,
            hosting: pack.hosting,
          },
          architecture: pack.architecture,
          conventions: pack.conventions,
          aiRules: pack.aiRules,
          gotchas: pack.gotchas,
        },
        null,
        2
      )

    default:
      return body
  }
}
