'use client'

import { useState } from 'react'
import type { Pack, OutputFormat } from '@/types'

const tabs: OutputFormat[] = ['CLAUDE.md', '.cursorrules', 'Markdown', 'JSON']

function generateOutput(pack: Pack, format: OutputFormat): string {
  const base = `# Project Context: ${pack.title}

## Stack
Framework: ${pack.framework}
Language: ${pack.language}
UI Library: ${pack.uiLib || 'None'}
Database: ${pack.db || 'None'}
Hosting: ${pack.hosting || 'None'}

## Architecture
${pack.architecture || 'Not specified.'}

## Coding Conventions
${pack.conventions || 'Not specified.'}

## AI Rules
${pack.aiRules || 'Not specified.'}

## Known Gotchas
${pack.gotchas || 'Not specified.'}`

  if (format === 'JSON') {
    return JSON.stringify(
      { title: pack.title, description: pack.description, generated_by: 'Brain Pack',
        stack: { framework: pack.framework, language: pack.language, uiLib: pack.uiLib, db: pack.db },
        architecture: pack.architecture, conventions: pack.conventions, aiRules: pack.aiRules, gotchas: pack.gotchas },
      null, 2
    )
  }
  if (format === '.cursorrules') return `# Cursor Rules — ${pack.title}\n\n${base}`
  if (format === 'CLAUDE.md') return `# ${pack.title}\n\n> Generated by Brain Pack — place in project root for Claude Code.\n\n${base}`
  return base
}

function renderHighlighted(text: string) {
  return text.split('\n').map((line, i) => {
    if (line.startsWith('# ') || line.startsWith('## '))
      return <div key={i} className="text-[var(--cx-accent)]">{line}</div>
    const colonIdx = line.indexOf(':')
    if (colonIdx > 0 && colonIdx < 20 && !line.startsWith(' '))
      return <div key={i}><span className="text-sky-400">{line.slice(0, colonIdx + 1)}</span><span className="text-[var(--text-primary)]">{line.slice(colonIdx + 1)}</span></div>
    return <div key={i} className="text-[var(--text-secondary)]">{line || '\u00A0'}</div>
  })
}

export default function OutputModal({ pack, onClose }: { pack: Pack; onClose: () => void }) {
  const [activeTab, setActiveTab] = useState<OutputFormat>('CLAUDE.md')
  const [copied, setCopied] = useState(false)
  const output = generateOutput(pack, activeTab)

  function handleCopy() {
    navigator.clipboard.writeText(output)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm" onClick={(e) => e.target === e.currentTarget && onClose()}>
      <div className="relative w-full max-w-2xl rounded-xl border border-[var(--bg-border)] bg-[var(--bg-surface)] overflow-hidden max-h-[85vh] flex flex-col shadow-2xl">
        <button onClick={onClose} className="absolute right-4 top-4 rounded-md p-1 text-[var(--text-muted)] hover:text-[var(--text-primary)] hover:bg-[var(--bg-elevated)] transition-colors z-10">
          <svg width="16" height="16" viewBox="0 0 16 16" fill="none"><path d="M4 4l8 8M12 4l-8 8" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/></svg>
        </button>

        <div className="p-6 pb-0">
          <p className="font-mono text-[11px] uppercase tracking-wider text-[var(--cx-accent)]">Context pack ready</p>
          <h2 className="mt-1.5 font-display text-xl text-[var(--text-primary)]">{pack.title}</h2>
        </div>

        <div className="flex gap-1 mt-4 px-6 border-b border-[var(--bg-border)]">
          {tabs.map((tab) => (
            <button key={tab} onClick={() => setActiveTab(tab)}
              className={`px-3 py-2.5 font-mono text-[11px] transition-colors rounded-t-md ${
                activeTab === tab ? 'border-b-2 border-[var(--cx-accent)] text-[var(--text-primary)] bg-[var(--bg-elevated)]/50' : 'text-[var(--text-muted)] hover:text-[var(--text-secondary)]'
              }`}
            >{tab}</button>
          ))}
        </div>

        <div className="overflow-y-auto flex-1 p-6">
          <div className="rounded-lg border border-[var(--bg-border)] bg-[var(--bg-base)] p-5 font-mono text-xs leading-relaxed">
            {renderHighlighted(output)}
          </div>
        </div>

        <div className="flex items-center justify-between border-t border-[var(--bg-border)] px-6 py-4">
          <p className="font-sans text-xs text-[var(--text-muted)]">
            ~{output.length.toLocaleString()} chars
          </p>
          <button onClick={handleCopy}
            className={`rounded-lg px-5 py-2 font-sans text-sm font-medium transition-all ${
              copied ? 'bg-[var(--bg-elevated)] text-[var(--cx-accent)]' : 'bg-[var(--cx-accent)] text-[var(--bg-base)] hover:bg-[var(--cx-accent-dim)]'
            }`}
          >
            {copied ? 'Copied!' : 'Copy to Clipboard'}
          </button>
        </div>
      </div>
    </div>
  )
}
